### ISSUE TITLE
Mists of RioV Crash before launch

### ISSUE THREAD

**Issue by Urrurrual** [SanAndreasP/SAPManagerPack#12]
In adding new mods to a modpack I started getting a crash before the client would launch.digging through the logs I found your haystack call and isolated the problem to the mists of RioV mod, but do not know where to go from here in order to resolve. relevant logs: http://pastebin.com/j1zZr4gp

**Comment by SanAndreasP** [comment]
I'll now close every issue in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
