### ISSUE TITLE
How to add custom hooks?

### ISSUE THREAD

**Issue by Starless2001** [SanAndreasP/SAPManagerPack#8]
You said we could use this coremod to add custom hooks, how do we do that? and which new events you already added? Im interested in 2 events: when the player held item gets changed and another when the player's armorInventory gets changed.

**Comment by SanAndreasP** [comment]
well, you fork it, create a new event*, add this event/hook via ASM and make a PR.
I'll review an possibly merge it.
*an event is not always necessary, see the horse armor hook.

To look on what hooks/events are already implemented (also to get a feel on how I do my ASM), see here:
https://github.com/SanAndreasP/SAPManagerPack/tree/master/java/de/sanandrew/core/manpack/transformer
https://github.com/SanAndreasP/SAPManagerPack/tree/master/java/de/sanandrew/core/manpack/util/event

**Comment by SanAndreasP** [comment]
I'm closing this issue, since this mod is now effectively retired.
