### ISSUE TITLE
Restart hook causes invalid credential login.

### ISSUE THREAD

**Issue by darkhax** [SanAndreasP/SAPManagerPack#9]
If you run the restartApp() method while the game has a username and password provided in the run arguments, you will get a failed authentication exception. This will only take place after the second restart attempt. 

https://gist.github.com/darkhax/242240debfc11413d3d7

**Comment by SanAndreasP** [comment]
The restart hook is a VERY hacky solution.
I actually wanted to remove (deactivate) the restart option until I have a better system in place.

**Comment by SanAndreasP** [comment]
I'm closing this issue, since this mod is now effectively retired.
